version: '2'
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: student
      MYSQL_USER: student_u
      MYSQL_PASSWORD: student_p

  phpfpm:
    image: php:fpm
    ports:
      - "9000:9000"
    volumes:
        - ./public:/usr/share/nginx/html
    links:
      - db
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - phpfpm
    volumes:
      - ./public:/usr/share/nginx/html
      - ./logs/nginx/:/var/log/nginx
